package dev.skidfuscator.config;

public class DefaultExempts {
    public static final String[] DEFAULT_EXEMPTS = {
            // Original mappings
            "class{^com\\/apache}",
            "class{^com\\/google}",
            "class{^com\\/sun}",
            "class{^java\\/}",
            "class{^javax\\/}",
            "class{^jdk\\/}",
            "class{^kotlin\\/.*}",
            "class{^org\\/apache}",
            "class{^org\\/bouncycastle}",
            "class{^org\\/eclipse}",
            "class{^org\\/hibernate}",
            "class{^org\\/jcp}",
            "class{^org\\/joda}",
            "class{^org\\/json}",
            "class{^org\\/jsoup}",
            "class{^org\\/mapleir}",
            "class{^org\\/objectweb}",
            "class{^org\\/slf4j}",
            "class{^org\\/springframework}",
            "class{^org\\/xml}",
            "class{^org\\/yaml}",
            "class{^sun\\/}",
            "class{^net\\/minecraft}",
            "class{^net\\/sf}",
            "class{^net\\/sourceforge}",
            "class{^net\\/dv8tion}",
            "class{.*it\\/unimi\\/dsi\\/fastutil\\/.*}",

            // Additional common dependencies
            "class{^com\\/fasterxml}",
            "class{^com\\/iwebpp}",
            "class{^com\\/neovisionaries}",
            "class{^com\\/sun\\/}",
            "class{^gnu\\/}",
            "class{^okhttp3\\/}",
            "class{^okio\\/}",
            "class{^org\\/apache\\/}",
            "class{^org\\/intellij}",
            "class{^org\\/jetbrains}",
            "class{^org\\/java_websocket}",
            "class{^org\\/slf4j\\/}",
            "class{^tomp2p\\/}",

            // Additional useful frameworks and libraries
            "class{^ch\\/qos\\/logback}",
            "class{^com\\/squareup}",
            "class{^com\\/thoughtworks}",
            "class{^io\\/netty}",
            "class{^jakarta\\/}",
            "class{^net\\/bytebuddy}",
            "class{^org\\/aspectj}",
            "class{^org\\/assertj}",
            "class{^org\\/checkerframework}",
            "class{^org\\/codehaus}",
            "class{^org\\/hamcrest}",
            "class{^org\\/junit}",
            "class{^org\\/mockito}",
            "class{^org\\/mozilla}",
            "class{^org\\/objenesis}",
            "class{^org\\/openjfx}",
            "class{^org\\/postgresql}",
            "class{^org\\/reactivestreams}",
            "class{^org\\/skyscreamer}",
            "class{^org\\/w3c}",
            "class{^software\\/amazon}",
    };
}